from HistoryPerson import HistoryPerson

Newton = HistoryPerson("Ньютон", "Физика")
Newton.status(Newton)
print(Newton)
print("Год рождения: ", Newton.year_birth)
print("Год смерти: ", Newton.year_death)
Newton.year_birth = Newton.setYear(1590)
print("Год рождения: ", Newton.year_birth)
print("АТРИБУТ 'Только для чтения': ", Newton._HistoryPerson__surname)
Newton._HistoryPerson__privateMethod()
print("Отрасль: ", Newton.industry)
delattr(Newton, "industry")

print("\n")

Galilei = HistoryPerson("Галилей", "Астрономия")
Galilei.status(Galilei)
print("Год рождения: ", Galilei.year_birth)
print("Год смерти: ", Galilei.year_death)
Galilei.year_death = Galilei.setYear(1675)
print("Год смерти: ", Galilei.year_death)
print("АТРИБУТ 'Только для чтения': ", Galilei._HistoryPerson__surname)
Galilei._HistoryPerson__privateMethod()
print("Отрасль: ", Galilei.industry)
delattr(Galilei, "industry")